language: node_js
node_js:
  - 'stable'
notifications:
  email:
    recipients:
      - juanc.jara@pucp.pe
    on_success: always
    on_failure: always
cache:
  directories:
    - node_modules
branches:
  only:
    - production
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: production
after_success:
  - 'npm run deploy'
